### ISSUE TITLE
Allow training resources that aren't youtube videos

### ISSUE THREAD

**Issue by rbuchberger** [rbuchberger/pd-aux-training#24]
- new model: training requirement
- videos are now a training resource which belongs to a requirement
- a requirement can have many resources
- add new types of resources - PDF files and images, for a start. 
- requirements take on the "has many users through training records"  relationship in place of videos

**Comment by Traches** [comment]
Don't have to do the whole thing before release, but it'll be easier if I build some of the models beforehand. That way I don't have to re-associate people's training records from videos to their respective training requirements.

**Comment by Traches** [comment]
Skeleton is there; now there are Lessons, and currently each Lesson has one video. Later I can enable multiple videos, and add other types of resources too.

**Comment by rbuchberger** [comment]
A year later, they don't really have need of this feature. Closing this, will reopen if necessary.
